# Generated by Django 4.1.2 on 2022-10-04 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bodega",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("type", models.CharField(max_length=120)),
                ("description", models.CharField(max_length=254, null=True)),
                ("stock", models.IntegerField()),
                (
                    "bodega_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.bodega",
                    ),
                ),
            ],
        ),
    ]
